info:
  contact: {}
paths:
  /user/:
    delete:
      parameters:
      - description: id
        in: query
        name: id
        type: string
      responses: {}
      summary: 删除用户
      tags:
      - 用户模块
    get:
      parameters:
      - description: id
        in: query
        name: id
        type: string
      responses: {}
      summary: 查询用户
      tags:
      - 用户模块
    post:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      responses: {}
      summary: 创建用户
      tags:
      - 用户模块
    put:
      parameters:
      - description: id
        in: query
        name: id
        type: string
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      responses: {}
      summary: 编辑用户
      tags:
      - 用户模块
  /user/list:
    get:
      responses: {}
      summary: 获取用户列表
      tags:
      - 用户模块
swagger: "2.0"
